name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: olegtarasov/get-tag@v1
        id: tag

      - name: Publish docker hub
        uses: tinact/docker.image@1.0.0
        with:
          image_name: sbaerlocher/autossh
          image_tag: ${{ steps.tag.outputs.tag }}
          dockerfile: .
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Publish github pkg
        uses: tinact/docker.image@1.0.0
        with:
          image_name: autossh
          image_tag: ${{ steps.tag.outputs.tag }}
          dockerfile: .
          registry: docker.pkg.github.com/sbaerlocher/docker.autossh
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}

  latest:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Docker image semver latest
        uses: tinact/docker.image-latest@1.0.0
        id: version
        with:
          image_name: sbaerlocher/autossh

      - name: Docker image retag docker hub
        uses: tinact/docker.image-retag@1.0.1
        with:
          image_name: sbaerlocher/autossh
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: registry.hub.docker.com
          registry_username: sbaerlocher
          registry_password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image retag github pkg
        uses: tinact/docker.image-retag@1.0.1
        with:
          image_name: autossh
          image_old_tag: ${{ steps.version.outputs.latest }}
          registry: docker.pkg.github.com/sbaerlocher/docker.autossh
          registry_username: sbaerlocher
          registry_password: ${{ secrets.GITHUB_TOKEN }}
